[package]
name = "librados-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
librados-sys = { path = "librados-sys" }
lazy_static = "1.5.0"
anyhow = "1.0.95"


[dev-dependencies]
tokio = { version = "^1.43",features = ["macros","rt"]}
tokio-macros = "~2.5.0"
futures = "^0.3"

